name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v2"

    - name: Load AWS Credentials
      uses: "aws-actions/configure-aws-credentials@v1"
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Backend Cloudformation
      uses: "aws-actions/aws-cloudformation-github-deploy@v1.0.3"
      id: deploy_backend
      with:
        name: lilsh-backend
        template: templates/template.yml
        capabilities: CAPABILITY_IAM
        parameter-overrides: WebsiteName=lil.sh,HostedZoneID=Z0843856IR07ISM8XVHB,CertificateArn=arn:aws:acm:us-east-1:934679804324:certificate/24823ff9-d324-4d26-aa6b-089a8d264a3c,FrontendDomain=get
        no-fail-on-empty-changeset: 1

    - name: Sync with S3
      uses: "jakejarvis/s3-sync-action@master"
      env:
        SOURCE_DIR: src
        AWS_S3_BUCKET: get.lil.sh

  deploy-api:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@master"

    - name: Load AWS Credentials
      uses: "aws-actions/configure-aws-credentials@v1"
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Use Node.js v12.18.3
      uses: "actions/setup-node@v1"
      with:
        node-version: 12.18.3
    - run: npm install

    - name: serverless deploy
      uses: "serverless/github-action@v1.53.0"
      with:
        args: deploy -s prod
