name: PullRequestMaster

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dev deps
        run: pip install -r requirements-dev.txt
      - name: Run Pytest
        run: python -m pytest api/tests/
